title: CI Admin Documentation
email: iqbalfawz@gmail.com
description: The only documentation for CI Admin project.
baseurl: ""
url: "http://iqbalfn.com"
twitter_username: iqbalfawz
github_username:  iqbalfn

# Build settings
markdown: kramdown